### ISSUE TITLE
Pitch Shift using FFT?

### ISSUE THREAD

**Issue by Mamena2020** [liamappelbe/fftea#40]
Hello. I'm wondering how I can use the FFT to change the pitch of audio data in pcm16 format. I've already been using this package [flutter ffmpeg](https://pub.dev/packages/ffmpeg_kit_flutter), which works great with this argument:
```
   "-i test.mp3 -af  asetrate=$sampleRate*$shift=$sampleRate,atempo=1/$shift output.mp3";
```
However, since this ffmpeg requires writing and reading files, it takes time to change the pitch on realtime. So, how does this FFT achieve pitch changes more efficiently?

**Comment by liamappelbe** [comment]
Good question. There's a few related algorithms in this area:

1. **Resampling** - changing to a different sampling rate, without changing the duration or pitch. You can also use resampling to change the duration and pitch without changing the sampling rate. This is easy to do with FFT and I'm planning to [add a util for this to the library](https://github.com/liamappelbe/fftea/issues/38). But also, depending on what API you're passing the audio to, you might be able to specify an arbitrary sample rate. For example, if you were writing a [WAV file](https://pub.dev/documentation/wav/latest/wav_file/Wav/Wav.html), you might be able to just give it whatever sample rate you want. Some audio playback APIs also let you specify an arbitrary sample rate. In that case resampling is totally unnecessary.
2. **Stretching** - changing the duration of the audio without changing the sampling rate or pitch. This is not so easy to do, and I'll talk about it more below.
3. **Pitch shifting** - changing the pitch, without changing the duration or sampling rate. If we have 1 and 2, we can combine them to do pitch shifting. For example, to shift up by an octave, you'd stretch the audio to twice the length, then resample to halve the length again, increasing the pitch.

So we really just need to figure out number 2. I've been meaning to look into this for a while, because it's not obvious how it's done, but it's clear that FFT is involved somehow. So I dug into it a bit today. I've skimmed the source code of [paulstretch](https://hypermammut.sourceforge.net/paulstretch/), and it seems the basic idea is to do a windowed STFT, followed by an inverse STFT *with a different chunk stride*. Also, all the FFT phases are randomized along the way.

It's a bit hard to explain in words, but [here's a picture](https://46dd8e9b-a-d30f3c5d-s-sites.googlegroups.com/a/paulnasca.com/site/algorithms-created-by-me/paulstretch_steps.png.1347380673301.png?attachauth=ANoY7coM_LHk-Fh1MyZruW-_ncHbzytC1uhyo4IeZKPv7lldJeReDVOs3U-wbEdmBnF05n8z76OxiVARacPw1edVONGmLAGm91oPYX4B5Ce3_2b16atodHfr1ikvY_cXHgqDV_60QOqYHTRHHLWDXgZBVHetiJ7I-12RTXyjZP2pIDyQn-g4OuG9uUcF-zbiSn5kS7tCUO5W4rf4LbJdwzMrCyf8MrOYinOvtMIToiIJjjxhm0eo9MVe0dLdRZC88YDAnG5xwJ11txQ5kNTw8JF1GfmpZvrXGw%3D%3D&attredirects=0). I think randomizing the phases is a stylistic choice, and I'm not sure it's what you want. If you don't want to randomize the phases then FFT might not even be necessary for this algorithm (you'll still need it for the resampling though). I'm going to try implementing it this afternoon and see what I find.

For your use case, it sounds like you want to do this transformation to a data stream. In that case your best bet is probably to do the resampling *during* the stretching, because the ordinary resampling algorithm needs the entire audio at once.

In any case, before any of this, you'll need to convert your audio from pcm16 to a `Float64List` (I have [a util](https://pub.dev/documentation/wav/latest/raw_file/readRawAudio.html) for this if you don't want to do it manually).

If this algorithm is too hard, I'm pretty sure you can use ffmpeg in streaming mode, rather than reading/writing files. I've done this before. You just need to tell it to read from stdin and write to stdout. Then you might be able to communicate directly with it using the [Dart Process API](https://api.dart.dev/stable/3.1.0/dart-io/Process-class.html). I haven't tried doing this via the Process API, but it should work. It's still starting up a subprocess, so it's not as efficient as writing the algorithm yourself, but at least you don't have to read/write files.

**Comment by liamappelbe** [comment]
@Mamena2020 Another question for you: How accurate do you need this to be? What are you wanting to use this for?

Doing more reading about audio stretching, and it seems it's still an active area of research. There's no perfect algorithm, and the best algorithms are pretty complicated. If you're fine with paulstretch or overlap-and-add, then this is something you can do yourself. But if you want something higher quality then you'll probably need to use something like [SBSMS](https://github.com/claytonotey/libsbsms) (you can load it using Dart FFI).

If you have audacity you can check out each of the 3 options I just mentioned. In the Effect > Pitch and Tempo menu, you'll see paulstretch and change tempo. In change tempo there's a checkbox for high quality. High quality stretching is using SBSMS, and low quality is using overlap and add. IMO, paulstretch is accurate enough for most purposes, and is much simpler than SBSMS. You can implement paulstretch pretty easily using my fft library.

**Comment by Mamena2020** [comment]
@liamappelbe My primary objective is to record audio and alter its pitch in real-time. The steps I'm currently working on are as follows:

1. Recording:
For recording, I'm using this package <a href="https://pub.dev/packages/flutter_sound">flutter sound</a> and streaming audio data in pcm16 format.

2. Auto Pitch:
To achieve pitch shifting, I'm using this <a href="https://pub.dev/packages/ffmpeg_kit_flutter">ffmpeg kit</a>. The process involves several steps:
     - Convert audio data from pcm to wav format.
     - Write the audio data (in wav format) to files.
     - Utilize FFmpeg arguments for applying the desired pitch shift.
     - Read the output audio data from file.
     - Play output audio `player.feedFromStream(outputAudio) ` using `FlutterSoundPlayer` from <a href="https://pub.dev/packages/flutter_sound">flutter sound </a>
     I have successfully accomplished this, but the real-time pitch shifting experience is not as smooth as I expected. This is likely too much steps used affecting real time performance.

i've try to use ffmpeg using the [Dart Process API](https://api.dart.dev/stable/3.1.0/dart-io/Process-class.html) as you suggest,  but seems not luck.
```
    
   Future<Uint8List> testAudio({required Uint8List audioData}) async {
    
      final additionalArguments = [
        '-af',
        'volume=1'
      ]; 

      final ffmpegProcess = await io.Process.start(
        'ffmpeg',
        [
          ...additionalArguments,
          '-i', 'pipe:0', // input
          '-f', 'wav', 'pipe:1', // output
        ],
        mode: io.ProcessStartMode.detachedWithStdio,
        runInShell: true,
      );
      ffmpegProcess.stdin.add(audioData);
      await ffmpegProcess.stdin.flush();
      await ffmpegProcess.stdin.close();
      ffmpegProcess.kill();
      final bytes = await ffmpegProcess.stdout.toBytes();
      return Uint8List.fromList(bytes);
  }

   extension StreamToBytes on Stream<List<int>> {
      Future<List<int>> toBytes() async {
        final chunks = await toList();
        final bytesBuilder = BytesBuilder();
        for (final chunk in chunks) {
          bytesBuilder.add(chunk);
        }
        return bytesBuilder.takeBytes();
      }
    }

```

**Comment by liamappelbe** [comment]
Ok, if streaming to an ffmpeg process doesn't work, try paulstretch. I think that's probably the simplest approach that will definitely work.

To recap:

1. [Convert](https://pub.dev/documentation/wav/latest/raw_file/readRawAudio.html) your chunk of pcm16 audio to a `Float64List`
2. Use [paulstretch](https://46dd8e9b-a-d30f3c5d-s-sites.googlegroups.com/a/paulnasca.com/site/algorithms-created-by-me/paulstretch_steps.png.1347380673301.png?attachauth=ANoY7coM_LHk-Fh1MyZruW-_ncHbzytC1uhyo4IeZKPv7lldJeReDVOs3U-wbEdmBnF05n8z76OxiVARacPw1edVONGmLAGm91oPYX4B5Ce3_2b16atodHfr1ikvY_cXHgqDV_60QOqYHTRHHLWDXgZBVHetiJ7I-12RTXyjZP2pIDyQn-g4OuG9uUcF-zbiSn5kS7tCUO5W4rf4LbJdwzMrCyf8MrOYinOvtMIToiIJjjxhm0eo9MVe0dLdRZC88YDAnG5xwJ11txQ5kNTw8JF1GfmpZvrXGw%3D%3D&attredirects=0) to stretch or shrink your audio by whatever ratio you need (eg to shift the audio up an octave, stretch by a factor of 2).
3. [Resample](https://github.com/liamappelbe/fftea/issues/38) your audio back to its original length.
4. Output the audio chunk.

If you implement it cleverly, you can combine steps 2 and 3, for increased efficiency. I'll probably add the resampling util soon, since I've pretty much already written it. Let me know if you need help with paulstretch.

**Comment by ivanesi** [comment]
Is it possible to detect pitch? For example like in ear training or guitar tuner apps.

**Comment by liamappelbe** [comment]
> Is it possible to detect pitch? For example like in ear training or guitar tuner apps.

@ivanesi Yep, this is easy. Just FFT your audio, find the frequency index with the largest magnitude, then use [`FFT.frequency`](https://pub.dev/documentation/fftea/latest/impl/FFT/frequency.html) to get the frequency in Hz of that index.

But if you have more questions, please file a separate bug. Don't hijack existing bugs with unrelated questions.
