### ISSUE TITLE
How to compare two wav file?

### ISSUE THREAD

**Issue by BigGitWorld** [liamappelbe/fftea#44]
Hello.
I have a reference wav file and wanna compare other wav files with it to check if same pattern is played or not.
I wrote the below code (Also I used [wav](https://pub.dev/packages/wav) package to read wav file data and [fl_chart](https://pub.dev/packages/fl_chart) to draw line charts).

```
import 'package:wav/wav.dart';
import 'package:fftea/fftea.dart';
...

    final Wav wav1 = await Wav.readFile("path-to-reference-sound.wav");
    List<double> wavData1 = wav1.channels[0];
    final fftxWav1 = FFT(wavData1.length);
    final freqListWav1 = fftxWav1.realFft(wavData1).discardConjugates().magnitudes();
    final List<double> decibelsWav1 = freqListWav1.map((amp) => 20 * math.log(amp) / math.ln10).toList();

    final Wav wav2 = await Wav.readFile("path-to-second-sound.wav");
    List<double> wavData2 = wav2.channels[0];
    final fftxWav2 = FFT(wavData2.length);
    final freqListWav2 = fftxWav2.realFft(wavData2).discardConjugates().magnitudes();
    final List<double> decibelsWav2 = freqListWav2.map((amp) => 20 * math.log(amp) / math.ln10).toList();

    for (int i = 0; i < decibelsWav1.length; ++i) {
      final freq = fftxWav1.frequency(i, 44100);
      chartPointsWave1.add(FlSpot(freq, freqListWav1[i]));
    }
    for (int i = 0; i < decibelsWav2.length; ++i) {
      final freq = fftxWav2.frequency(i, 44100);
      chartPointsWave2.add(FlSpot(freq, freqListWav2[i]));
    }
```
Now I can draw 2 line charts from ``chartPointsWave1`` and ``chartPointsWave2``.
Is this approach true?
Could you please suggest me a solution?

**Comment by liamappelbe** [comment]
The first question to ask yourself, when comparing these two sounds, is what differences do you want to ignore?

If you just want to check if the wavs are exactly the same, then you don't need FFT at all. You can just compare the 2 arrays of samples to make sure all the values are the same. So the question is what sorts of differences are allowed?

- Are differences in volume/amplitude allowed?
- Adding small amounts of noise?
- Compression artifacts?
- Is frequency filtering allowed? Eg low pass filter?
- Time shifts? Are you trying to locate a short sound in a much longer sound?
- Other noises? Are you trying to detect one instrument in a song?

You need to be more clear about what you mean by comparing the sounds.

**Comment by liamappelbe** [comment]
Ok, try using [`STFT`](https://pub.dev/documentation/fftea/latest/stft/STFT-class.html). This will break the sounds into chunks and give you FFTs of each chunk. The chunks should be small enough to give you good time resolution, but not so small that you lose important frequency info. 10-100ms (441 to 4410 samples) should work.

There will be 2 kinds of chunk you see: chunks with the buzzer sound, and chunks that are just noise. To tell the difference, compare the amplitude of the [buzzer frequency](https://pub.dev/documentation/fftea/latest/stft/STFT/indexOfFrequency.html) to the *average amplitude* of all the frequencies. For buzzer chunks, the buzzer frequency will have a much larger amplitude than the other frequencies. You'll have to experiment with a good threshold for this ratio (maybe plot the ratio over time to pick a good threshold).

So the `STFT` gives you a stream of chunk FFTs, and then you decide if each chunk is a buzzer chunk. So at this point you essentially have a stream of `bool`s (where true means it's a buzzer chunk). So then you can write a function that looks for a particular stream of bools. For example, if you're expecting 5 beeps in a row, and each beep is 2 seconds long, with a gap of 1 second between, and your chunk size is 100ms, then you're looking for a bool stream that looks like this:

```
[...false][20 * true][10 * false][20 * true][10 * false][20 * true][10 * false][20 * true][10 * false][20 * true][false...]
```

Though you should allow for +/- a few trues and falses, because the `STFT` chunk boundaries likely won't line up with the start and end of the buzzer. So expect 18-22 trues, and 8-12 falses in this example. Again you'll have to experiment.

Note that once you've analyzed the reference file to find the buzzer frequency etc, you don't actually need to `STFT` the reference file at runtime. Just `STFT` the test files and look for those patterns.

**Comment by BigGitWorld** [comment]
This is my reference-buzzer.wav analyzed by the ``Audacity`` app.
![Screenshot from 2023-12-04 15-50-59](https://github.com/liamappelbe/fftea/assets/28644637/15c59e92-eedc-48ea-bf52-e7e2177cb78c)
As you can see, I extracted the following info:
```
time duration of wav file: 6 seconds
number of beep: 5
time duration between each beep: 300 milliseconds
